language: cpp
sudo: required
dist: trusty

env:
    global:
        - PREMAKE_DIR=$TRAVIS_BUILD_DIR/Premake
        - RAKNET_DIR=$TRAVIS_BUILD_DIR/RakNet
    matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - gcc-5
            - gcc-5-multilib
            - g++-5
            - g++-5-multilib
            - unzip

cache:
  directories:
    - RakNet

before_install:
    - sudo -E dpkg --add-architecture i386
    - sudo -E apt-get -yq update

install:
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install linux-libc-dev:i386
    
before_script:

    - if [ ! -f "${RAKNET_DIR}/CMakeLists.txt" ]; then git clone https://github.com/WopsS/RakNet.git; fi

    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz
    - tar xzf premake-*-linux.tar.gz -C ${PREMAKE_DIR}

    - mkdir -p ${RAKNET_DIR}/Build
    - mkdir ${TRAVIS_BUILD_DIR}/Libs

script:
    - cd ${RAKNET_DIR}/Build
    - CC=gcc-5 CXX=g++-5 cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DRAKNET_ENABLE_SAMPLES=OFF -DRAKNET_ENABLE_DLL=OFF -DRAKNET_GENERATE_INCLUDE_ONLY_DIR=ON
    - make CXX=g++-5

    - ln -s ${RAKNET_DIR}/include/RakNet ${TRAVIS_BUILD_DIR}/Includes/Common
    - ln -s ${RAKNET_DIR}/Build/Lib/LibStatic/libRakNetLibStatic.a ${TRAVIS_BUILD_DIR}/Libs

    - cd ${PREMAKE_DIR}
    - chmod 755 ./MakeGMakeProjects.sh
    - ./MakeGMakeProjects.sh
    - cd Projects
    - make CONFIG=${BUILD_TYPE} CXX=g++-5