version: '{build}'
image: Visual Studio 2015
clone_depth: 1

configuration:
    - Debug
    - Release

environment:
    MINHOOK_DIR: '%APPVEYOR_BUILD_FOLDER%\minhook'
    PREMAKE_DIR: '%APPVEYOR_BUILD_FOLDER%\Premake'
    RAKNET_DIR: '%APPVEYOR_BUILD_FOLDER%\RakNet'

pull_requests:
    do_not_increment_build_number: true

install:
    - git submodule update --init --recursive

    - git clone --depth=1 https://github.com/TsudaKageyu/minhook.git
    - git clone --depth=1 https://github.com/WopsS/RakNet.git

    - appveyor DownloadFile https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-windows.zip
    - 7z x  premake-*-windows.zip -o"%PREMAKE_DIR%"

before_build:
    - mkdir "%RAKNET_DIR%\Build"

    - mkdir "%APPVEYOR_BUILD_FOLDER%\Includes\Common"
    - mkdir "%APPVEYOR_BUILD_FOLDER%\Includes\Client"
    
    - mkdir "%APPVEYOR_BUILD_FOLDER%\Libs"

build_script:
    - cd "%MINHOOK_DIR%\build\VC14"
    - MSBuild.exe "MinHookVC14.sln" /verbosity:minimal /p:Configuration=%CONFIGURATION%

    - cd "%RAKNET_DIR%\Build"
    - cmake .. -G "Visual Studio 14 2015" -DRAKNET_GENERATE_INCLUDE_ONLY_DIR=ON -DRAKNET_ENABLE_DLL=OFF -DRAKNET_ENABLE_SAMPLES=OFF
    - MSBuild.exe "RakNet.sln" /verbosity:minimal /p:Configuration=%CONFIGURATION%

    - mklink "%APPVEYOR_BUILD_FOLDER%\Includes\Client\MinHook.h" "%MINHOOK_DIR%\include\MinHook.h"
    - mklink /D "%APPVEYOR_BUILD_FOLDER%\Includes\Common\RakNet" "%RAKNET_DIR%\include\RakNet"

    - mklink "%APPVEYOR_BUILD_FOLDER%\Libs\libMinHook.x86.lib" "%MINHOOK_DIR%\build\VC15\lib\%CONFIGURATION%\libMinHook.x86.lib"
    - mklink "%APPVEYOR_BUILD_FOLDER%\Libs\RakNetLibStatic.lib" "%RAKNET_DIR%\Build\Lib\LibStatic\%CONFIGURATION%\RakNetLibStatic.lib"

    - cd "%PREMAKE_DIR%"
    - MakeVS2015Projects.bat
    - cd Projects
    - MSBuild.exe "SA-MP+.sln" /verbosity:minimal /p:Configuration=%CONFIGURATION%

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%\Build\Server"
    - mkdir plugins
    - move samp-plus*.* plugins

artifacts:
    - path: Build\Client
      name: samp-plus-client
      type: zip

    - path: Build\Server
      name: samp-plus-server
      type: zip